version: "1"
services:
  - type: web
    name: pulselhub-space
    env: node
    region: frankfurt
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20.10.0"
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        sync: false
